### ISSUE TITLE
[DOCS] 기획 확정 및 문서 작성

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/E2E2-TALKKA#1]
## Todo
- [x] 사용자의 의도를 파악하여 핵심기능 정의
- [x] 부가기능 정의
- [x] 기술 스택 정의 및 DB 스키마 정의
  - [x] ERD 작성
- [x] Figma 와어프레임 작성
