### ISSUE TITLE
[FEAT] EC2 배포 환경 구성

### ISSUE THREAD

**Issue by ss0ngcode** [Kernel360/E2E2-TALKKA#123]
## 기능
- 배포를 위한 EC2 환경 구성
## Todo
- [x] Docker에 DB, Server, Nginx container 구성
- [x] Nginx ssl 적용
- [x] CI / CD 구성
- [x] 개발용 / 배포용 환경 구성
