### ISSUE TITLE
[FEAT] HTTP Exception 처리 

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/E2E2-TALKKA#16]
## 기능
- HTTP Exception 에 관련된 base class 
- 각 에러 status 에 대한 Exception class
  - BAD_REQUEST
  - UNAUTHORIZED
  - FORBIDDEN
  - NOT_FOUND
  - ...
- 해당 Exception 을 처리할 수 있는 Handler 구성

## Todo
- [ ] HTTP Base Exception class 작성
- [ ] HTTP Error 상황에 대한 Exception class 작성
- [ ] Exception handler 작성
