### ISSUE TITLE
[FEAT]  프로젝트 초기화

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/E2E2-TALKKA#2]
## 기능
- Spring Boot Project 를 추가합니다.
- 로컬 작업용 MySQL Docker compose 를 추가합니다.
- 협업용 Formatter / Checkstyle 을 추가합니다.

## Todo
- [x] Spring boot:3.3.2 모듈 추가
- [x]  Lombok, Spring Web, Spring Data JPA, Spring Security 의존성 추가
- [x]  로컬 DB 작업용 MySQL 8.4 (LTS) Docker compose 로 추가
- [x]  Application.yaml 기본 설정 추가
- [x] .env.sample 추가
