### ISSUE TITLE
[DOCS] 데이터 설계 및 ERD 작성

### ISSUE THREAD

**Issue by ss0ngcode** [Kernel360/E2E2-TALKKA#4]
## TODO
- [x] 유저 도메인 데이터 설계
- [x] 버스 도메인 데이터 설계
- [x] 지하철 도메인 데이터 설계
- [x] 리뷰 도메인 데이터 설계
