### ISSUE TITLE
[FEAT]  FE - Next.js 기틀 마련 / 로그인 / 리뷰

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/E2E2-TALKKA#45]
## 기능
- FE 작업을 위한 기본 레이아웃 구성
- 협업 가능한 Next.js 토대 마련
- 소셜 로그인 구현
- 버스 리뷰 페이지 구현

## Todo
- [x] Nest.js UI Kit 선정 / template 활용
- [x] `/login` 페이지 구현
- [x] `/logout` 페이지 구현
- [x] `/review` `/review/bus` `/review/bus/modify` `/review/bus/create` 페이지 구현
