### ISSUE TITLE
[DOCS] 기획 구체화 및 데이터 정의

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/E2E2-TALKKA#5]
## TODO
 - [x] 요구사항 정리
 - 세부 기능 구체화
   - [x] 사용자 뷰 정의
   - [x] 회원가입 및 로그인 방식 결정
 - 필요한 데이터 정의
   - [x] 버스 관련 데이터 정의
   - [x] 지하철 관련 데이터 정의
 - [x] 외부 API 정의
