### ISSUE TITLE
[FEAT] 지하철 도메인 엔티티 및 레포지토리 구현

### ISSUE THREAD

**Issue by ss0ngcode** [Kernel360/E2E2-TALKKA#56]
## 기능
- 지하철에 관련된 엔티티 생성 및 레포지토리 구현
## Todo
- [ ] 지하철 역 엔티티 구현
- [ ] 지하철 혼잡도 엔티티 구현
- [ ] 지하철 시간표 엔티티 구현
- [ ] 각 레포지토리 구현
