### ISSUE TITLE
[FEAT] 엔티티 작성

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/E2E2-TALKKA#6]
## 기능
- 현재 ERD 에 정의된 테이블을 Entity 로 정의합니다.
## Todo
- [ ] 버스 노선 정보
- [ ] 노선 경유 정류장
- [ ] 버스 위치 정보
- [ ] 회원
- [ ] 버스 리뷰
- [ ] 지하철 리뷰
