### ISSUE TITLE
[FEAT] 북마크 도메인 구현

### ISSUE THREAD

**Issue by Gyaak** [Kernel360/E2E2-TALKKA#64]
## 기능
- 북마크 도메인 구현
- 북마크 상세 도메인 구현
## Todo
**- [ ] 해당 기능을 개발하기 위해서 필요한 작업을 명시해주세요**
- [x] 북마크 엔티티 구현
- [x] 북마크 상세 엔티티 구현
- [x] 북마크 dto 구현
- [x] 북마크 상세 dto 구현
