### ISSUE TITLE
[REFACTOR] Bus 관련 Refactoring 

### ISSUE THREAD

**Issue by ss0ngcode** [Kernel360/E2E2-TALKKA#91]
## 기능
- Bus 관련 DTO / Controller / Exception 처리 변경
- VO 필요한 부분 작성
- 테스트 코드 변경
## Todo
- [ ] Exception 처리 scope를 controller 로 변경
  - exception response 에 대한 처리를 controller 에서 수행
- [ ] 필요한 VO 객체 생성
- [ ] 테스트 코드 재작성
